/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GameCard: typeof import('./src/components/games/GameCard.vue')['default']
    GameCarousel: typeof import('./src/components/games/GameCarousel.vue')['default']
    GameList: typeof import('./src/components/games/GameList.vue')['default']
    LayBacktop: typeof import('@layui/layui-vue')['LayBacktop']
    LayButton: typeof import('@layui/layui-vue')['LayButton']
    LayException: typeof import('@layui/layui-vue')['LayException']
    LaySkeleton: typeof import('@layui/layui-vue')['LaySkeleton']
    LaySkeletonItem: typeof import('@layui/layui-vue')['LaySkeletonItem']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToolTips: typeof import('./src/components/base/ToolTips.vue')['default']
  }
}
