/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GameCard: typeof import('./src/components/Games/GameCard.vue')['default']
    GameCarousel: typeof import('./src/components/games/GameCarousel.vue')['default']
    GameList: typeof import('./src/components/games/GameList.vue')['default']
    LayButton: typeof import('@layui/layui-vue')['LayButton']
    LayCarousel: typeof import('@layui/layui-vue')['LayCarousel']
    LayCarouselItem: typeof import('@layui/layui-vue')['LayCarouselItem']
    LayException: typeof import('@layui/layui-vue')['LayException']
    ListCard: typeof import('./src/components/ListCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
